dns-server:
  image: sameersbn/bind:latest
  net: host
  volumes:
    - /docker/bind:/data
  ports:
    - "53:53"
    - "10000:10000"

dhcp-server:
  image:networkboot/dhcpd:latest
  net: host
  volumes: 
    - /docker/dhcpd:/data

unifi-controller:
  image: jacobalberty/unifi:latest
  net: host
  volumes:
    - /docker/unifi/lib:/var/lib/unifi
    - /docker/unifi/log:/var/log/unifi
    - /docker/unifi/run:/var/run/unifi
  ports:
    - "8080:8080"
    - "8081:8081"
    - "8443:8443"
    - "8843:8843"
    - "8880:8880"
    - "3478:3478"
